### ISSUE TITLE
Dataset for outside China 

### ISSUE THREAD

**Issue by asahinyener** [983632847/USCL#2]
Hello, baidu has strict requirements about foreign country registration. Would you be able to provide a google drive  link or  of any provider you choose?

Thanks in advance

**Comment by 983632847** [comment]
Hi, You can download the demo Butterfly dataset from [Google drive](https://drive.google.com/file/d/1zefZInevopumI-VdX6r7Bj-6pj_WILrr/view?usp=sharing)

**Comment by asahinyener** [comment]
Hi, thanks for your response; the google drive link seems to be locked down. I have requested access under the email of asahinynr@gmail.com
